# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "stage", "qa" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: list out the files
      run: ls -la
    - name: lets see the target folder and verify the jar file
      run: cd target && ls -la
    - name: public ip address fetch
      run: curl ifconfig.me
    - name: upload artifact
      run: curl -ukwilshan@gmail.com:James.725 -T target/spring-test-1.0.jar "https://thecloudworld.jfrog.io/artifactory/tcw-generic-local/v1.0"
  #  - name: run the microservice for verification
  #    run: cd target && nohup java -jar spring-test-1.0.jar &